runtime: java17 # or another supported runtime
entrypoint: java -Xmx64m -jar demo.jar
env: flex
instance_class: F2
handlers:
  - url: .*
    script: auto
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
service_account: axiomatic-set-282904@appspot.gserviceaccount.com